### PR TITLE
Enable Travis-ci and fix the gem on ruby 2.3

### LINKED ISSUE #2: Configure CI
Since CircleCI is deprecated let's use Shopify-Build

### PR DESCRIPTION
**Pull request by Edouard-chin**
Fix #2

### CODE REVIEW

File: lib/deprecation_toolkit/warning.rb [hunk 1]
```diff
@@ -2,6 +2,8 @@
 
 module DeprecationToolkit
   module Warning
+    extend self
```
Comment (rafaelfranca) [inline lib/deprecation_toolkit/warning.rb]: I think this will now work because there is no `super` to call in the `else` on < 2.5

File: .travis.yml [hunk 2]
```diff
@@ -0,0 +1,11 @@
+sudo: false
+cache: bundler
+language: ruby
+before_install:
+  - gem update bundler
+rvm:
+  - 2.3.0
```
Comment (rafaelfranca) [inline .travis.yml]: remove the `.0` to be able to run with the newest version of the series.

**Comment by Edouard-chin** [comment]
Should now be good

File: lib/deprecation_toolkit/warning.rb [hunk 3]
```diff
@@ -2,25 +2,35 @@
 
 module DeprecationToolkit
   module Warning
-    def warn(str)
+    extend self
+
+    def deprecation_triggered?(str)
       if DeprecationToolkit::Configuration.warnings_treated_as_deprecation.any? { |warning| warning =~ str }
         ActiveSupport::Deprecation.warn(str)
```
Comment (rafaelfranca) [inline lib/deprecation_toolkit/warning.rb]: It seems strange that a predicate method is actually executing action. Also it is relying on the fact that `ActiveSupport::Deprecation.warn` returns a truthy value.

I think splint this in two methods and doing a `if/else` inside `Warning` and `Kernel` is clear.
